version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=SDPLabs
      - POSTGRESQL_USER=sdplabsuser
      - POSTGRESQL_PASSWORD=sdplabsuser
    ports:
      - "5441:5432"
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/
    ports:
      - '5672:5672'
      - '15672:15672'